<Project>
  <ItemGroup>
    <_SiteimproveModuleFiles Include="$(MSBuildThisFileDirectory)../../contentFiles/any/net10.0/modules/_protected/**/*" />
    <Content Update="@(_SiteimproveModuleFiles)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <Target Name="SiteimproveCopyProtectedModules" BeforeTargets="PrepareForBuild">
    <Copy SourceFiles="@(_SiteimproveModuleFiles)"
          DestinationFolder="$(MSBuildProjectDirectory)/modules/_protected/%(RecursiveDir)"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
